---
# tasks file for ansible-role-landir.git_n_config
- name: Update apt cache (Debian).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'
  #when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Ensure git is installed (Debian).
  apt:
    name:
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libssl-dev
      - zlib1g-dev
      - build-essential
      - gcc
      - git
    state: present
  when: ansible_os_family == 'Debian'

- name: configure git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  with_items: "{{ git_config_values }}"
  become: false
